#+TITLE: Modelování a simulace
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
* Úvod
** Základní pojmy
*** Systém
Je soubor elementárních částí, které mají mezi sebou určíté vazby.
*** Model
Napodobenina systému jiným systémem
*** Modelování
Vyrváření modelů systémů
*** Simulace
Získávání nových znalostí o systémz experimentováním s jeho modelech

** Základní etapy modelování a simulace
1. Vytvoření abstraktního modelu
2. Vytvoření simulačního modelu
3. Verifikace a validace
4. Simulace
5. Analýza a interpretace výsledků

** Formální definice systému
Systém $S$ je dvojice
\[S = (U, R)\]

kde:
*** $U$ je konečná množina prvků systému:
\[U = \{u_1, u_2, \dots, u_N\}\]

*** Prvek systému $u = (X, Y)$:
**** $X$ je množina všech vstupních proměnných
**** $Y$ je množina všech výstupních proměnných

*** Charakteristika systému $R$ je množina všech propojení
\[R = \bigcup^{N}_{i,j=1} R_{ij}\]

*** Propojení prvku $u_i$ s prvkem $u_j$:
\[R_{ij} \subseteq Y_i \times X_j\]

** Čas
Rozlišujeme tři typy času:
1. Reálný času
   Probíháý skutečný děj v reálném systému
2. Modelový čas
   Časová osa modelu, nemusí být synchronní s reálným časem
3. Strojový čas
   Čas spotřebovaný na výpočet programu

** Časová množína
Množina všech časových okamžiků, ve kterých jsou definovány hodnoty vstupních,
stavových a výstupních proměnných prvku systému

Může být diskrétní nebo spojitá[fn:continuous]

** Chování systému
Každému časovému průběhu vstupu přiřazuje časový průběh výstupu. Lze definovat
jako zobrazení.

Systémy považujeme za systémy se stejným chováním, vyvolají-li stejné podněty u
obou systémů stejné reakce.

Izomorfní systémy jsou systémy, kde prvky systémů navzájem můžeme přiřadit 1:1.

Homomorfní systémy jsou systémy, kde prvky systémů navzájem můžeme přiřadit N:1,
ale ne naopak.

** Okolí systému
Okolí systému zahrnuje vše, co má vliv na chování systému, ale není jeho
součástí.

Systémy můžeme rozdělit na uzavřené (nekomunikují s okolím nebo jej zanedbábají)
a otevřene (mají definované vstupy a výstupy).

** Klasifikace prvků systémů
*** Klasifikace 1
Prvky se spojitým chováním vs prvky s diskrétním chováním
*** Klasifikace 2
Prvky s deterministickým chováním vs prvky s nedeterministickým chováním

** Klasifikace systémů
Typ systému závisí na typu jeho prvků
*** Klasifikace 1
Spojité, Diskrétní, Kombinované
*** Klasifikace 2
Deterministické, nedeterministické

** Simulace
Cílem simulace je získat nové informace o chování systému v závislosti na
vstupních veličinách a na hodnotách parametrů.

Opakovaně vyhodnocujeme model, tak dlouho, dokud nezískáme dostatek informací o
chování systému nebo dokud nenalezneme takové hodnoty parametrů, pro něž má
systém žádané chování.

** Typy simulace podle modelu
Spojitá, diskrétní, kombinovaná. Kvalitativní, kvantitativní.

** Typy simulace podle simulátoru
Na počítači, real-time, paralelní a distribuovaná

** Verifikace modelu
Měla by předcházet simulaci. Ověťujeme, zda simulační model odpovídá 1:1
(izomorfně) abstraktnímu modelu.

** Validace modelu
Jedná se o jeden z nejobtížnějších problémů modelování. Vyžaduje neustálou
konfrontaci informací a modelovaném systému a dat ze simulovaného systému.

Nelze absolutně dokázat přesnost modelu. Pokud chování modelu neodpovídá
předpokládanému chování systému, musíme model modifikovat.


* Diskrétní simulace
** Úvod
** Petriho sítě
** Systémy hromadné obsluhy
** SIMLIB

* Spojitá simulace
** Úvod
** Numerické metody
** SIMLIB

* Kombinovaná simulace
** Úvod
** SIMLIB

* Footnotes

[fn:continuous] Na číslicovém počítači se vždy diskretizuje
